"""Add nearby_places to complaints

Revision ID: 4e601dead164
Revises: 20260331_0003
Create Date: 2026-04-10 09:56:01.138036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4e601dead164'
down_revision: Union[str, None] = '20260331_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('nearby_places', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'nearby_places')
    # ### end Alembic commands ###
